//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AjaxJqueryJsonSample.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Contact
    {
        public int ContactId { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNo { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
    }
}
